### ISSUE TITLE
[FEAT]: Auto-repeat hotkey on hold

### ISSUE THREAD

**Issue by sitiom** [LGUG2Z/whkd#27]
**Is your feature request related to a problem? Please describe.**
I can't hold down `alt + oem_plus` and `alt + oem_minus` to resize windows in whkd like I can in AHK.

**Describe the solution you'd like**
whkd should auto-repeat hotkey on hold, similar to AHK behavior.

**Comment by LGUG2Z** [comment]
I think this could be due to this in the upstream library: https://github.com/dnlmlr/windows-hotkeys/blob/4316fa1424753be49143e430c5ad33069b363575/src/singlethreaded.rs#L77

When I find some time I'll try to fork it and see if this is indeed the case and see if the owner is open to integrating a PR which makes this behaviour configurable.

**Comment by LGUG2Z** [comment]
I made this change on a local fork and it allows auto-repetitions; I'll open an issue on the repo and see if the author is interested in this sort of change.

**Comment by LGUG2Z** [comment]
Released here: https://github.com/LGUG2Z/whkd/releases/tag/v0.2.0
Implementation video here: https://www.youtube.com/watch?v=kjw5SJhyPCk
